name: Test Schedule

on:
  schedule:
    - cron: '1 1 1 1 1'   # כל דקה
  workflow_dispatch:       # מאפשר הרצה ידנית

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This is a test run at $(date -u)"
